-- Create a table for public profiles
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  avatar_url text,
  website text,
  role text,

  constraint username_length check (char_length(username) >= 3)
);

-- Set up Row Level Security (RLS)
-- See https://supabase.com/docs/guides/auth/row-level-security
alter table profiles
  enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

-- This trigger automatically creates a profile entry when a new user signs up via Supabase Auth.
-- See https://supabase.com/docs/guides/auth/managing-user-data#using-triggers for more details.
create function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url, role)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url', 'user');
  return new;
end;
$$ language plpgsql security definer;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Create a table for reports
create table reports (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  disease_name text,
  disease_name_hindi text,
  patient_count integer,
  severity text,
  trend text,
  user_id uuid references auth.users
);

-- Set up RLS for reports
alter table reports
  enable row level security;

create policy "Reports are viewable by everyone." on reports
  for select using (true);

create policy "Kendra can insert reports." on reports
  for insert with check (exists (select 1 from profiles where profiles.id = auth.uid() and profiles.role = 'kendra'));

-- Create a table for alerts
create table alerts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  alert_message text,
  location text,
  severity text
);

-- Set up RLS for alerts
alter table alerts
  enable row level security;

create policy "Alerts are viewable by everyone." on alerts
  for select using (true);

create policy "Kendra can insert alerts." on alerts
  for insert with check (exists (select 1 from profiles where profiles.id = auth.uid() and profiles.role = 'kendra'));

create policy "Kendra can update alerts." on alerts
  for update using (exists (select 1 from profiles where profiles.id = auth.uid() and profiles.role = 'kendra'));

create policy "Kendra can delete alerts." on alerts
  for delete using (exists (select 1 from profiles where profiles.id = auth.uid() and profiles.role = 'kendra'));

-- Create a table for predictions
create table predictions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  disease text,
  disease_hindi text,
  probability integer,
  risk_level text,
  peak_expected text,
  prevention_tips text[]
);

-- Set up RLS for predictions
alter table predictions
  enable row level security;

create policy "Predictions are viewable by everyone." on predictions
  for select using (true);

-- Create a table for stocks
create table stocks (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  medicine_name text,
  stock integer,
  min_stock integer,
  user_id uuid references auth.users
);

-- Set up RLS for stocks
alter table stocks
  enable row level security;

create policy "Kendra can view their own stocks." on stocks
  for select using (auth.uid() = user_id);

create policy "Kendra can insert stocks." on stocks
  for insert with check (auth.uid() = user_id and exists (select 1 from profiles where profiles.id = auth.uid() and profiles.role = 'kendra'));

create policy "Kendra can update their own stocks." on stocks
  for update using (auth.uid() = user_id and exists (select 1 from profiles where profiles.id = auth.uid() and profiles.role = 'kendra'));
